-- 1. PROFILES (Extends Auth Users)
-- Robust schema with Idempotency and Security Best Practices

BEGIN;

-- Drop the table and any dependent objects (CASCADE removes dependent objects)
DROP TABLE IF EXISTS public.profiles CASCADE;

-- Recreate the profiles table
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  email text,
  full_name text,
  role text DEFAULT 'user',
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Allow authenticated users to select only their own profile
CREATE POLICY profiles_select_own ON public.profiles
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = id);

-- Allow authenticated users to insert only their own profile
CREATE POLICY profiles_insert_own ON public.profiles
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = id);

-- Allow authenticated users to update only their own profile
CREATE POLICY profiles_update_own ON public.profiles
  FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = id)
  WITH CHECK ((SELECT auth.uid()) = id);

-- Trigger function to auto-create profile on auth.user creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Insert profile when a new auth.user is created.
  -- Use COALESCE to avoid null constraint errors if fields are missing.
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data ->> 'full_name')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- Revoke execution from public to secure the function
REVOKE EXECUTE ON FUNCTION public.handle_new_user FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user FROM anon, authenticated;

-- Drop an existing trigger with the same name if present, then create it
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

COMMIT;


-- 2. TEAM MEMBERS
create table public.team_members (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Owner of the data
  name text not null,
  role text,
  phone text,
  birth_date date,
  type text check (type in ('staff', 'kid', 'volunteer')), 
  status text default 'Ativo',
  avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.team_members enable row level security;
create policy "Users can CRUD their own team." on team_members for all using (auth.uid() = user_id);

-- 3. TASKS
create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  text text not null,
  type text, -- 'semanal', 'mensal', 'urgente'
  done boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.tasks enable row level security;
create policy "Users can CRUD their own tasks." on tasks for all using (auth.uid() = user_id);

-- 4. EVENTS
create table public.events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  date date not null,
  time time,
  type text, -- 'Local', 'Sede', etc.
  focus text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.events enable row level security;
create policy "Users can CRUD their own events." on events for all using (auth.uid() = user_id);

-- 5. FINANCE (TRANSACTIONS)
create table public.finance_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  description text not null,
  amount numeric not null,
  type text check (type in ('income', 'expense')),
  date date not null,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.finance_transactions enable row level security;
create policy "Users can CRUD their own finance." on finance_transactions for all using (auth.uid() = user_id);

-- 6. SNACKS
create table public.snacks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  quantity integer,
  cost numeric,
  event_id bigint references public.events,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.snacks enable row level security;
create policy "Users can CRUD their own snacks." on snacks for all using (auth.uid() = user_id);
